name: SpaceONE Github Action Deploy

on:
  workflow_dispatch:
    inputs:
      dest:
        description: 'target repository({repository_name} or {topic1/topic2})'
        required: true
        default: 'identity'
      sync_only:
        description: 'sync only flag'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set git user
        run : git config --global user.email admin@cloudforet.io
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: deploy
        run: |
          python src/main.py --dest ${{ github.event.inputs.dest }} --type repository

  master_push:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.sync_only }}
    needs: deploy
    steps:
      - uses: actions/checkout@v2
      - name: set git user
        run : git config --global user.email admin@cloudforet.io
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          event-type: master_push
